services:
  indexer:
    build:
      context: ./indexer
    restart: always
    ports:
      - "3001:3001"
    networks:
      - mud-sqlite-network
    env_file:
      - path: ./.env
        required: true
      - path: ./indexer/.env
        required: true
    volumes:
      - indexer-data:/data
  explorer:
    build:
      context: ./world-explorer
    restart: always
    depends_on:
      indexer:
        condition: service_started
    ports:
      - "13690:13690"
    networks:
      - mud-sqlite-network
    env_file:
      - path: ./.env
        required: true
      - path: ./world-explorer/.env
        required: true
    volumes:
      - indexer-data:/data:ro
  admin:
    image: ghcr.io/coleifer/sqlite-web:latest
    depends_on:
      indexer:
        condition: service_started
    ports:
      - "8086:8080"
    networks:
      - mud-sqlite-network
    env_file:
      - path: ./admin/.env
        required: true
    volumes:
      - indexer-data:/data:ro

volumes:
  indexer-data:
    driver: local

networks:
  mud-sqlite-network:
    name: mud-sqlite-network
